### ISSUE TITLE
Use slash commands whereever possible

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/Reaper#2]
Spectre uses `$` as a prefix as an indicator for commands.
In general slash commands are better for this as they can also display useful descriptions and from a UX perspective are nicer when it comes to parsing args as well.

**EDIT:** Ok Reaper apparently also already uses Slash commands but they don't seem to work rn? Maybe perms issue?

**Comment by Bobbyperson** [comment]
From what I'm looking at all of these commands are `@commands.hybrid_command` which makes them normal and slash commands. To actually create them in discord you need a command or an `on_ready` listener to run `await self.client.tree.sync()`. I'll check if this already exists and make a PR if necessary when I get home.

**Comment by Bobbyperson** [comment]
Upon further inspection there is a `$sync` command. As long as the bot was invited with permission to create commands (if not you will have to re-invite it), using the sync command should create every slash command.
![image](https://github.com/user-attachments/assets/1b160029-a33a-4f05-a5b1-f3e8a60235dc)

**Comment by GeckoEidechse** [comment]
Can confirm seems to work 
![image](https://github.com/user-attachments/assets/6e672354-736e-4ded-b99f-f62e86fce3fd)

Although newly added commands don't seem to show up after sync. Not sure if that's a cache thing or another issue.

**Comment by Bobbyperson** [comment]
Syncing has a cooldown of something like 30s IIRC, and from my usage of it on my own bot slash commands are a total pain to get working ever. I think it takes a few minutes to register after adding one.

**Comment by GeckoEidechse** [comment]
Yeah so basically we already do this after all so essentially closing as completed lol
