### ISSUE TITLE
Handle FlightCore error message in regards to default install path

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/Reaper#55]
![image](https://github.com/user-attachments/assets/76dc36bb-1495-4649-abb1-4f766039f151)

Respond with link to or contents of https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#cannot-write-log-file-when-using-northstar-on-ea-app

**Comment by Bobbyperson** [comment]
To be clear, this would happen after an image is OCR'd, correct?

**Comment by GeckoEidechse** [comment]
Yes
